name: tutorial
channels:
  - defaults
dependencies:
  - torch==1.9.0
  - torchaudio==0.9.0
  - torchvision==0.10.0

  - absl-py==1.1.0
  - antlr4-python3-runtime==4.9.3
  - appnope==0.1.3
  - asttokens==2.0.5
  - attrs==21.4.0
  - backcall==0.2.0
  - black==22.3.0
  - cachetools==5.2.0
  - certifi==2022.6.15
  - charset-normalizer==2.1.0
  - click==8.0.4
  - cloudpickle==2.1.0
  - cycler==0.11.0
  - Cython==0.29.30
  - dataclasses==0.6
  - decorator==5.1.1
  - executing==0.8.3
  - fairscale==0.4.6
  - fire==0.4.0
  - fonttools==4.34.4
  - future==0.18.2
  - fvcore==0.1.5.post20220512  
  - google-auth==2.9.1
  - google-auth-oauthlib==0.4.6
  - grpcio==1.47.0
  - hydra-core==1.2.0
  - idna==3.3
  - imageio==2.19.3
  - imantics==0.1.12  
  - imgaug==0.4.0
  - importlib-metadata==4.12.0
  - iopath==0.1.9
  - python==8.4.0
  - jedi==0.18.1
  - jsonschema==4.7.2
  - kiwisolver==1.4.3
  - labelme2coco==0.2.1
  - lxml==4.9.1
  - Markdown==3.3.7
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.3
  - mypy-extensions==0.4.3
  - networkx==2.8.4 
  - numpy==1.23.1
  - oauthlib==3.2.0
  - omegaconf==2.2.2
  - opencv-python==4.6.0.66
  - packaging==21.3
  - pandas==1.4.3
  - parso==0.8.3
  - pathspec==0.9.0
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==9.2.0
  - platformdirs==2.5.2
  - portalocker==2.5.1
  - prompt-toolkit==3.0.30
  - protobuf==3.19.4
  - psutil==5.9.1
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pybboxes==0.1.3
  - pycocotools==2.0.4
  - pydot==1.4.2
  - Pygments==2.12.0
  - pyparsing==3.0.9
  - PyQt5==5.15.7
  - PyQt5-Qt5==5.15.2
  - PyQt5-sip==12.11.0
  - pyrsistent==0.18.1
  - python-dateutil==2.8.2
  - pytz==2022.1
  - PyWavelets==1.3.0
  - PyYAML==6.0
  - requests==2.28.1
  - requests-oauthlib==1.3.1
  - rsa==4.8
  - sahi==0.10.1
  - scikit-image==0.19.3
  - scipy==1.8.1
  - seaborn==0.11.2
  - Shapely==1.8.2
  - six==1.16.0
  - stack-data==0.3.0
  - tabulate==0.8.10
  - tensorboard==2.9.1
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - termcolor==1.1.0
  - terminaltables==3.1.10
  - thop==0.1.1.post2207130030
  - tifffile==2022.5.4
  - timm==0.6.5
  - tomli==2.0.1
  - tqdm==4.64.0
  - traitlets==5.3.0
  - typing_extensions==4.3.0
  - urllib3==1.26.10
  - wcwidth==0.2.5
  - Werkzeug==2.1.2
  - xmljson==0.2.1
  - yacs==0.1.8
  - zipp==3.8.1
  - pip
  - pip:
    - mlflow